# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en

fr:
  languageCode: fr
  title: French website title..
  contentDir: content/fr


zh:
  languageCode: zh-Hans
  title: Chinese website title..
  contentDir: content/zh