# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  menu:
    main:
      - name: Members
        url: members
        weight: 10
      - name: Research
        url: research
        weight: 20
      - name: Publications
        url: publications
        weight: 30
      - name: News
        url: news
        weight: 40
      - name: Join
        url: join
        weight: 50

fr:
  languageCode: fr
  title: French website title..
  contentDir: content/fr
  params:
    description: Site description in French...
  menu:
    main:
      - name: Membres
        url: people
        weight: 10
      - name: Plateformes
        url: event
        weight: 20
      - name: Ouvrages
        url: publication
        weight: 30
      - name: Nouvelles
        url: post
        weight: 40
      - name: Rejoindre
        url: contact
        weight: 50

zh:
  languageCode: zh-Hans
  title: Chinese website title..
  contentDir: content/zh
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: 成员
        url: people
        weight: 10
      - name: 平台
        url: event
        weight: 30
      - name: 出版物
        url: publication
        weight: 40
      - name: 消息
        url: post
        weight: 20
      - name: 加入
        url: contact
        weight: 50